syntax = "proto3";
package com.huanggenghg.easyipc_transport_aidl;

// 封装一个完整的远程方法调用请求
message IpcRequest {
    string requestId = 1;         // 用于匹配异步响应的唯一ID
    string serviceName = 2;       // 目标服务标识符
    string methodName = 3;        // 要调用的方法名
    bool isAsync = 4;             // 是否异步调用

    // 参数列表：
    repeated bytes parameters = 5;       // 每个参数的序列化数据（例如JSON字节流）
    repeated string parameterTypes = 6;  // 每个参数的完整类名（如 com.example.User）
}

// 封装远程调用的结果或错误信息
message IpcResponse {
    string requestId = 1;         // 对应请求的ID

    bool isError = 2;             // 是否发生错误
    string errorMessage = 3;      // 错误信息（如果isError为true）

    // 结果数据：
    bytes resultData = 4;         // 返回值的序列化数据
    string resultType = 5;        // 返回值的完整类名
}
